---
name: Variables y Procedimientos
locale: es
type: learning
beta: false
teacher_info: ''
language: python
id_format: "%05d"
order:
- 6
- 9
- 10
- 5
- 1
- 11
- 2
- 13
- 14
- 4
- 3
- 12
private: false
